server:
  port: 8010
#应用名称 nacos会将该名称当做服务名称
spring:
  application:
    name: order-service-sentinel
  cloud:
    nacos:
        server-addr: localhost:8848
        discovery:
          username: nacos
          password: nacos
          namespace: public
    loadbalancer:
      ribbon:
        enabled : false
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      web-context-unify: false
#springboot默认日志级别是info fegin的debug日志级别就不会输入
logging:
  level:
    com.order.fegin: debug

# fegin超时时间配置
feign:
  client:
    config:
      default:
        logger-level: full
        connect-timeout: 3000
        read-timeout: 3000

