server:
  port: 8010
#应用名称 nacos会将该名称当做服务名称
spring:
  application:
    name: order-service
  cloud:
    nacos:
        server-addr: localhost:8847
        discovery:
          username: nacos
          password: nacos
          namespace: public
stock-service:
  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
    NFLoadBalancerRuleClassName: com.ribbon.rule.CustomRule