server:
  port: 8070
#应用名称 nacos会将该名称当做服务名称
spring:
  application:
    name: order-service-sentinel
  cloud:
    loadbalancer:
      ribbon:
        enabled : false
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      web-context-unify: false
      datasource:
        flow-rule: #可以自定义
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            data-id: order-service-sentinel-flow-rule
            rule-type: flow

feign:
  sentinel:
    enabled: true
