server:
  port: 8030
#应用名称 nacos会将该名称当做服务名称
spring:
  application:
    name: prodcut-service
  cloud:
    nacos:
        server-addr: localhost:8848
        discovery:
          username: nacos
          password: nacos
          namespace: public
    loadbalancer:
      ribbon:
        enabled : false
